### ISSUE TITLE
Python app can not connect to DataSF

### ISSUE THREAD

**Issue by eoneoff** [prakhar1989/FoodTrucks#17]
App.py failes to connect to http://data.sfgov.org/resource/rqzj-sfat.json and quits with error message

Traceback (most recent call last):
  File "app.py", line 121, in <module>
    check_and_load_index()
  File "app.py", line 43, in check_and_load_index
    load_data_in_es()
  File "app.py", line 15, in load_data_in_es
    r = requests.get(url)
  File "/usr/local/lib/python2.7/dist-packages/requests/api.py", line 69, in get
    return request('get', url, params=params, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests/api.py", line 50, in request
    response = session.request(method=method, url=url, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests/sessions.py", line 468, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests/sessions.py", line 576, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests/adapters.py", line 423, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPConnectionPool(host='data.sfgov.org', port=80): Max retries exceeded with url: /resource/rqzj-sfat.json (Caused by NewConnectionError('<requests.packages.urllib3.connection.HTTPConnection object at 0x7ff546c74350>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution',))

I run the container on Docker Toolbox on Windows 10. I a browser I can access the url and get a json object.

**Comment by despot** [comment]
Hi @freeernest

Got the same "I run the container on Docker Toolbox on Windows 10. I a browser I can access the url and get a json object." as @eoneoff eoneoff . So this seems still not fixed with the last commit. 

Kind Regards

**Comment by prakhar1989** [comment]
Sorry I don't have a windows machine to test this on, but I just tested and everything is good to go. Can you test again? I think  http://data.sfgov.org/resource/rqzj-sfat.json  was temporarily unavailable when you tried?

**Comment by prakhar1989** [comment]
Closing this as I haven't heard back. Feel free to reopen if the issue persists.
